services:
  prowjack:
    build: .
    container_name: prowjack
    restart: unless-stopped
    network_mode: "service:gluetun"
#    networks:
#      - npm-net
#    ports:
#      - "7014:7014"
    env_file:
      - ./.env
    environment:
      - PORT=7014
      - ADDON_PUBLIC_URL=
    volumes:
      - /media/vinicius/Arquivos:/data             # ← compartilhado com qBittorrent





